const Locations = {
    "1": { name: "Kolkata", id: 1 },
    "2": { name: "Delhi", id: 2 },
    "3": { name: "Mumbai", id: 3 },
    "4": { name: "Bangalore", id: 4 },
    "5": { name: "Chennai", id: 5 },
    "6": { name: "Hyderabad", id: 6 },
    "7": { name: "Ahmedabad", id: 7 },
    "8": { name: "Pune", id: 8 },
    "9": { name: "Jaipur", id: 9 },
    "10": { name: "Surat", id: 10 },
    "11": { name: "Lucknow", id: 11 },
    "12": { name: "Kanpur", id: 12 },
    "13": { name: "Nagpur", id: 13 },
    "14": { name: "Patna", id: 14 },
    "15": { name: "Indore", id: 15 },
    "16": { name: "Thane", id: 16 },
    "17": { name: "Bhopal", id: 17 },
    "18": { name: "Visakhapatnam", id: 18 },
    "19": { name: "Vadodara", id: 19 },
    "20": { name: "Firozabad", id: 20 },
    "21": { name: "Ludhiana", id: 21 },
    "22": { name: "Rajkot", id: 22 },
    "23": { name: "Agra", id: 23 },
    "24": { name: "Siliguri", id: 24 },
    "25": { name: "Nashik", id: 25 },
    "26": { name: "Faridabad", id: 26 },
    "27": { name: "Patiala", id: 27 },
    "28": { name: "Meerut", id: 28 },
    "29": { name: "Kalyan-Dombivali", id: 29 },
    "30": { name: "Vasai-Virar", id: 30 }
}

export default Locations;
  